import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./componets/Header";
import NextAuthProvider from "./context/provider";
import { Suspense } from "react";
import Loading from "./atoms/loading";
import Image from "next/image";

const notoSansJp = Noto_Sans_JP({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "lecture-review",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansJp.className}>
        <NextAuthProvider>
          <div className="fixed top-0 w-full h-screen z-[-1] ">
            <Image //全体背景画像
              src={"/backgroundImage.png"}
              alt="background"
              layout="fill"
              objectFit="cover"
            />
          </div>
          <Header />
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </NextAuthProvider>
      </body>
    </html>
  );
}
